---
language: python
services: docker

env:
  global:
    - ROLE_NAME: hetzner_installimage

before_script:
  - docker-compose up -d

script:
  # Run tests.
  - docker-compose exec molecule molecule test --all

after_script:
  - docker-compose down

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
