---
- name: check if software raid status is set in hetzner_installimage_install_raid
  set_fact:
    sw_raid_status: "{{ item.split(' ') | last| int }}"
  when: item is match("SWRAID") and item is not match("SWRAIDLEVEL")
  with_items: "{{ hetzner_installimage_install_raid | default([]) }}"

- name: check if software raid level is set in hetzner_installimage_install_raid
  set_fact:
    sw_raid_level: "{{ item.split(' ') | last | int }}"
  when: item is match("SWRAIDLEVEL")
  with_items: "{{ hetzner_installimage_install_raid | default([]) }}"

- name: automatically determine disk number
  shell: |
    set -o pipefail
    lsblk | grep disk
  args:
    executable: /bin/bash
  register: disk_number
  changed_when: false

- name: fail playbook if no disk was found using lsblk
  fail:
    msg: unsufficient number of disks detected
  when: disk_number.stdout_lines|length < 1

- name: fail playbook if more than 2 disks were found using lsblk
  fail:
    msg: unsufficient number of disks detected
  when: disk_number.stdout_lines|length > 2

- name: set automatic software raid status for single disk when not set in config
  set_fact:
    sw_raid_status: 0
  when: disk_number.stdout_lines|length == 1 and sw_raid_status is not defined

- name: set automatic software raid level for single disk when not set in config
  set_fact:
    sw_raid_level: 0
  when: disk_number.stdout_lines|length == 1 and sw_raid_level is not defined

- name: set automatic software raid status for 2 disks when not set in config
  set_fact:
    sw_raid_status: 1
  when: disk_number.stdout_lines|length == 2 and sw_raid_status is not defined

- name: set automatic software raid level 1 for 2 disks when not set in config
  set_fact:
    sw_raid_level: 1
  when: disk_number.stdout_lines|length == 2 and sw_raid_level is not defined

- name: automatically determine first disk device
  shell: |
    set -o pipefail
    lsblk | grep disk | awk '{split($0, a, " "); print a[1]}' | sort | head -1 | tail -1
  args:
    executable: /bin/bash
  register: first_disk_device
  changed_when: false

- name: automatically determine second disk device for raid level 1
  shell: |
    set -o pipefail
    lsblk | grep disk | awk '{split($0, a, " "); print a[1]}' | sort | head -2 | tail -1
  args:
    executable: /bin/bash
  register: second_disk_device
  when: sw_raid_status == 1
  changed_when: false

- name: set hetzner_installimage_install_raid values when not defined
  set_fact:
    hetzner_installimage_install_raid:
      - SWRAID {{ sw_raid_status }}
      - SWRAIDLEVEL {{ sw_raid_level }}
  when: hetzner_installimage_install_raid is not defined

- name: set hetzner_installimage_install_drives value for no raid / single disk
  set_fact:
    hetzner_installimage_install_drives:
      - DRIVE1 /dev/{{ first_disk_device.stdout }}
  when: sw_raid_status == 0

- name: set hetzner_installimage_install_drives value for raid 1
  set_fact:
    hetzner_installimage_install_drives:
      - DRIVE1 /dev/{{ first_disk_device.stdout }}
      - DRIVE2 /dev/{{ second_disk_device.stdout }}
  when: sw_raid_status == 1
