---

- name: copy public key into tempfile
  shell: /usr/bin/tail -1 /root/.ssh/authorized_keys > tmpKey

- name: copy autosetup configuration file
  template:
    src: installimage.j2
    dest: /autosetup
    owner: root
    group: root
    mode: 0644

- name: run installimage
  command: /root/.oldroot/nfs/install/installimage -K /root/tmpKey
  register: result

- name: reboot server
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: remove server from local known_hosts file
  local_action: shell ssh-keygen -R {{ ansible_host }}

- name: pause a bit for the reboot to kick in
  pause: seconds=60

- name: waiting for server to come back
  local_action: wait_for
    host={{ inventory_hostname }}
    port=22
    delay=1
    timeout=180

- name: create hostcode
  copy:
    content: "{{ ansible_host | md5 }}"
    dest: /etc/hostcode

...
