---
- name: check existence of /etc/hostcode
  stat:
    path: /etc/hostcode
  register: hetzner_installimage_hostcode
  when: not hetzner_installimage_ignore_hostcode == True

- name: Set default value for hetzner_installimage_run
  set_fact: 
    hetzner_installimage_run: True

- name: Overwrite hetzner_installimage_run when conditons match
  set_fact: 
    hetzner_installimage_run: False
  when: (hetzner_installimage_ignore_hostcode is not defined or not hetzner_installimage_ignore_hostcode == True) and (hetzner_installimage_hostcode is defined and hetzner_installimage_hostcode.stat.exists == True)

- name: fail playbook if image is not supposed to be installed
  fail:
    msg: "File /etc/hostcode exists on host {{ansible_host}}. Set hetzner_installimage_ignore_hostcode=True to force installation."
  when: not hetzner_installimage_run

- name: include rescue mode handling tasks
  include: rescuemode.yml
  when: hetzner_installimage_run and not ansible_check_mode

- name: include installimage handling tasks
  include: installimage.yml
  when: hetzner_installimage_run and not ansible_check_mode
