---
- name: Confirm install for each host
  pause:
    prompt: "Really wipe all host data and install fresh OS image on host {{ item }} (y/n) ?"
  with_items: "{{ play_hosts }}"
  register: reset_host
  run_once: true
  delegate_to: localhost
  when: hetzner_installimage_user_confirmations is not defined or hetzner_installimage_user_confirmations[item] is not defined

- name: Initialize hetzner_installimage_user_confirmations variable
  set_fact:
    hetzner_installimage_user_confirmations: {}
  run_once: true
  delegate_to: localhost
  when: hetzner_installimage_user_confirmations is not defined

- name: Add user confirmation for each host
  set_fact:
    hetzner_installimage_user_confirmations: "{{ hetzner_installimage_user_confirmations | combine({item.item: item.user_input}) }}"
  with_items: "{{ reset_host.results }}"
  run_once: true
  delegate_to: localhost
  when: item.user_input is defined

- name: Set default value for hetzner_installimage_run
  set_fact:
    hetzner_installimage_run: true

- name: Overwrite hetzner_installimage_run when confirmation was not successful
  set_fact:
    hetzner_installimage_run: false
  when: hetzner_installimage_user_confirmations[inventory_hostname] is not defined or hetzner_installimage_user_confirmations[inventory_hostname] != 'y'

- name: Check existence of /etc/hetzner_installimage_provisioned.flag if possible
  block:
    - name: Check existence of /etc/hetzner_installimage_provisioned.flag
      stat:
        path: /etc/hetzner_installimage_provisioned.flag
      register: hetzner_installimage_provisioned_flag
      when: not hetzner_installimage_ignore_provisioned_flag
      ignore_errors: yes
  ignore_unreachable: true # if an error is returned here the host might not have the ssh key yet
  when: hetzner_installimage_run

- name: Hosts that can not be connected due to mising ssh key should not be marked as unavailable
  meta: clear_host_errors

- name: Overwrite hetzner_installimage_run when conditons match
  set_fact:
    hetzner_installimage_run: false
  when: |
    (hetzner_installimage_ignore_provisioned_flag is not defined or not hetzner_installimage_ignore_provisioned_flag)
    and (hetzner_installimage_provisioned_flag.stat is defined and hetzner_installimage_provisioned_flag.stat.exists)

- name: Include rescue mode handling tasks
  include: rescuemode.yml
  when: hetzner_installimage_run and not ansible_check_mode

- name: Include installimage handling tasks
  include: installimage.yml
  when: hetzner_installimage_run and not ansible_check_mode
