---
# note: when the server was booted into rescue mode already it will still return active = false
# active = true only appears when rescue mode was activated but the system not yet re-booted 
- name: check the current rescue mode state
  uri:
    url: "{{ hetzner_installimage_robot_api_base_url }}/boot/{{ hetzner_installimage_ansible_host_ip }}/rescue"
    method: GET
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: hetzner_installimage_rescue
  when: hetzner_installimage_run

- name: activate rescue mode
  uri:
    url: "{{ hetzner_installimage_robot_api_base_url }}/boot/{{ hetzner_installimage_ansible_host_ip }}/rescue"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "os=linux&arch=64&authorized_key={{ hetzner_installimage_key_fingerprint }}"
    status_code: 200
    body_format: form-urlencoded
  delegate_to: localhost
  when: not hetzner_installimage_rescue.json.rescue.active

- name: Execute hardware reset
  uri:
    url: "{{ hetzner_installimage_robot_api_base_url }}/reset/{{ hetzner_installimage_ansible_host_ip }}"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "type=hw"
    status_code: 200
    body_format: form-urlencoded
  delegate_to: localhost
  register: reset

- name: Check that known_hosts file exists
  stat:
    path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
  register: stat_known_hosts_result

- name: remove server from local known_hosts file
  command: ssh-keygen -R {{ ansible_host }}
  delegate_to: localhost
  changed_when: false
  when: stat_known_hosts_result.stat.exists == true 

- name: pause a bit for the hardware reset to kick in
  pause:
    seconds: "{{ hetzner_installimage_reboot_pause }}"
  delegate_to: localhost

- name: waiting for server to come back
  wait_for:
    host: "{{ hetzner_installimage_wait_for_host }}"
    port: 22
    delay: 1
    timeout: 180
  delegate_to: localhost
