---
- name: Converge
  hosts: all
  tasks:
    - name: Execute role's main task running the whole installimage procedure
      include_role:
        name: ansible-role-hetzner_installimage
      vars:
        hetzner_installimage_robot_api_base_url: http://hetzner-robot:3000
        hetzner_installimage_webservice_username: "robot"
        hetzner_installimage_webservice_password: "secret"
        hetzner_installimage_run: true
        hetzner_installimage_key_fingerprint: "fi:ng:er:pr:in:t0:00:00:00:00:00:00:00:00:00:00"
        user_confirmations:
          debian9: y
          debian10: y
          Ubuntu16: y
          Ubuntu18: y